E-Shop/E-Shop/Controllers/AdminProductController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Context;
using EntityLayer.Entities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;

namespace E_Shop.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminProductController : Controller
    {
        // GET: AdminProduct

        ProductRepository productRepository=new ProductRepository();
        DataContext db = new DataContext();
        public ActionResult Index(int sayfa=1)
        {
            return View(productRepository.List().ToPagedList(sayfa,3));
        }


        public ActionResult Create()
        {
            List<SelectListItem> deger1 = (from i in db.Categories.ToList()
            select new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            }).ToList();
        ViewBag.ktgr = deger1;
        return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(Product data,HttpPostedFileBase File)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Hata Oluştu");
            }

            string path = Path.Combine("~/Content/Image/" + File.FileName);
            File.SaveAs(Server.MapPath(path));
            data.Image = File.FileName.ToString();
            productRepository.Insert(data);
            return RedirectToAction("Index");
        }


        public ActionResult Delete(int id)
        {
            var delete = productRepository.GetById(id);
            productRepository.Delete(delete);
            return RedirectToAction("Index");

        }

        public ActionResult Update(int id)
        {
            List<SelectListItem> deger1 = (from i in db.Categories.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.Name,
                                               Value = i.Id.ToString()
                                           }).ToList();
            ViewBag.ktgr = deger1;

            var update=productRepository.GetById(id);
            return View(update);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Update(Product data, HttpPostedFileBase File)
        {
            var update = productRepository.GetById(data.Id);
            if (!ModelState.IsValid)
            {
                if (File == null)
                {
                    update.Description = data.Description;
                    update.Name = data.Name;
                    update.IsApproved = data.IsApproved;
                    update.Popular = data.Popular;
                    update.Price = data.Price;
                    update.Stock = data.Stock;
                    update.CategoryId = data.CategoryId;
                    productRepository.Update(data);
                    return RedirectToAction("Index");
                }
                else
                {
                    update.Description = data.Description;
                    update.Name = data.Name;
                    update.IsApproved = data.IsApproved;
                    update.Popular = data.Popular;
                    update.Price = data.Price;
                    update.Stock = data.Stock;
                    update.Image = data.Image;
                    update.CategoryId = data.CategoryId;
                    productRepository.Update(update);
                    return RedirectToAction("Index");
                }
            }
            return View(update);
           

        }

        public ActionResult CriticalStock()
        {
            var kritik = db.Products.Where(x => x.Stock <= 50).ToList();
            return View(kritik);
        }

        public PartialViewResult StockCount()
        {
            if (User.Identity.IsAuthenticated)
            {
                var count = db.Products.Where(x => x.Stock < 50).Count();
                ViewBag.count = count;
                var azalan = db.Products.Where(x => x.Stock == 50).Count();
                ViewBag.azalan = azalan;    
            }
            return PartialView();
        }

    }
}

E-Shop/E-Shop/Views/Shared/AdminLayout.cshtml
<link href="~/NiceAdmin/css/bootstrap-theme.css" rel="stylesheet">
<!--external css-->
<!-- font icon -->
<link href="~/NiceAdmin/css/elegant-icons-style.css" rel="stylesheet" />
<link href="css/font-awesome.min.css" rel="stylesheet" />
<!-- full calendar css-->
<link href="~/NiceAdmin/assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css" rel="stylesheet" />
<link href="~/NiceAdmin/assets/fullcalendar/fullcalendar/fullcalendar.css" rel="stylesheet" />
<!-- easy pie chart-->
<link href="~/NiceAdmin/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen" />
<!-- owl carousel -->
<link rel="stylesheet" href="~/NiceAdmin/css/owl.carousel.css" type="text/css">
<link href="~/NiceAdmin/css/jquery-jvectormap-1.2.2.css" rel="stylesheet">
<!-- Custom styles -->
<link rel="stylesheet" href="~/NiceAdmin/css/fullcalendar.css">
<link href="~/NiceAdmin/css/widgets.css" rel="stylesheet">
<link href="~/NiceAdmin/css/style.css" rel="stylesheet">
<link href="~/NiceAdmin/css/style-responsive.css" rel="stylesheet" />
<link href="~/NiceAdmin/css/xcharts.min.css" rel=" stylesheet">
<link href="~/NiceAdmin/css/jquery-ui-1.10.4.min.css" rel="stylesheet">
<link href="~/Content/PagedList.css" rel="stylesheet" />
<!-- =======================================================
  Theme Name: NiceAdmin
  Theme URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  Author: BootstrapMade
  Author URL: https://bootstrapmade.com
======================================================= -->
</head>

<body>
    <!-- container section start -->
    <section id="container" class="">


        <header class="header dark-bg">
            <div class="toggle-nav">
                <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="icon_menu"></i></div>
            </div>

            <!--logo start-->
            <a href="index.html" class="logo">E-SHOP <span class="lite">Admin</span></a>
            <!--logo end-->

            <div class="nav search-row" id="top_menu">
                <!--  search form start -->
                <ul class="nav top-menu">
                    <li>
                        <form class="navbar-form">
                            <input class="form-control" placeholder="Search" type="text">
                        </form>
                    </li>
                </ul>
                <!--  search form end -->
            </div>

            <div class="top-nav notification-row">
                <!-- notificatoin dropdown start-->
                <ul class="nav pull-right top-menu">


                    <li id="alert_notificatoin_bar" class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">

                            <i class="icon-bell-l"></i>
                            <span class="badge bg-important">7</span>
                        </a>
                        <ul class="dropdown-menu extended notification">
                            <div class="notify-arrow notify-arrow-blue"></div>
                            <li>
                                <p class="blue">You have 4 new notifications</p>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="label label-primary"><i class="icon_profile"></i></span>
                                    Friend Request
                                    <span class="small italic pull-right">5 mins</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="label label-warning"><i class="icon_pin"></i></span>
                                    John location.
                                    <span class="small italic pull-right">50 mins</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="label label-danger"><i class="icon_book_alt"></i></span>
                                    Project 3 Completed.
                                    <span class="small italic pull-right">1 hr</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="label label-success"><i class="icon_like"></i></span>
                                    Mick appreciated your work.
                                    <span class="small italic pull-right"> Today</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">See all notifications</a>
                            </li>
                        </ul>
                    </li>
                    <!-- alert notification end-->
                    <!-- user login dropdown start-->
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="profile-ava">
                                <img alt="" src="~/NiceAdmin/img/avatar1_small.jpg">
                            </span>
                            <span class="username">Jenifer Smith</span>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu extended logout">
                            <div class="log-arrow-up"></div>
                            <li class="eborder-top">
                                <a href="#"><i class="icon_profile"></i> My Profile</a>
                            </li>
                            <li>
                                <a href="#"><i class="icon_mail_alt"></i> My Inbox</a>
                            </li>
                            <li>
                                <a href="#"><i class="icon_clock_alt"></i> Timeline</a>
                            </li>
                            <li>
                                <a href="#"><i class="icon_chat_alt"></i> Chats</a>
                            </li>
                            <li>
                                <a href="login.html"><i class="icon_key_alt"></i> Log Out</a>
                            </li>
                            <li>
                                <a href="documentation.html"><i class="icon_key_alt"></i> Documentation</a>
                            </li>
                            <li>
                                <a href="documentation.html"><i class="icon_key_alt"></i> Documentation</a>
                            </li>
                        </ul>
                    </li>
                    <!-- user login dropdown end -->
                </ul>
                <!-- notificatoin dropdown end-->
            </div>
        </header>
        <!--header end-->
        <!--sidebar start-->
        <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu">

                    <li>
                        <a href="/AdminCategory/Index">

                            <span>Kategoriler</span>
                        </a>
                    </li>
                    <li>
                        <a href="/AdminProduct/Index">

                            <span>Ürünler</span>

                        </a>

                    </li>

                    <li>
                        <a href="/AdminProduct/CriticalStock">

                            <span>Kritik Stok  @Html.Action("StockCount", "AdminProduct")</span>

                        </a>

                    </li>
                    <li>
                        <a href="/AdminSales/Index">

                            <span>Satıslar</span>

                        </a>

                    </li>


                    <li>
                        <a href="/Admin/UserList">

                            <span>Kullanıcılar</span>

                        </a>

                    </li>

                    @*<li>
                        <a href="/AdminIstatistic/Index">

                            <span>İstatistikler</span>

                        </a>

                    </li>*@

                    <li>
                        <a href="/Admin/Comment">

                            <span>Yorumlar</span>

                        </a>

                    </li>


                </ul>
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">
                @RenderBody()

            </section>

        </section>
        <!--main content end-->
    </section>
    <!-- container section start -->
    <!-- javascripts -->
    <script src="~/NiceAdmin/js/jquery.js"></script>
    <script src="~/NiceAdmin/js/jquery-ui-1.10.4.min.js"></script>
    <script src="~/NiceAdmin/js/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="js/jquery-ui-1.9.2.custom.min.js"></script>
    <!-- bootstrap -->
    <script src="~/NiceAdmin/js/bootstrap.min.js"></script>
    <!-- nice scroll -->
    <script src="~/NiceAdmin/js/jquery.scrollTo.min.js"></script>
    <script src="~/NiceAdmin/js/jquery.nicescroll.js" type="text/javascript"></script>
    <!-- charts scripts -->
    <script src="~/NiceAdmin/assets/jquery-knob/js/jquery.knob.js"></script>
    <script src="~/NiceAdmin/js/jquery.sparkline.js" type="text/javascript"></script>
    <script src="~/NiceAdmin/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js"></script>
    <script src="~/NiceAdmin/js/owl.carousel.js"></script>
    <!-- jQuery full calendar -->
    <
    <script src="~/NiceAdmin/js/fullcalendar.min.js"></script>
    <!-- Full Google Calendar - Calendar -->
    <script src="~/NiceAdmin/assets/fullcalendar/fullcalendar/fullcalendar.js"></script>
    <!--script for this page only-->
    <script src="~/NiceAdmin/js/calendar-custom.js"></script>
    <script src="~/NiceAdmin/js/jquery.rateit.min.js"></script>
    <!-- custom select -->
    <script src="~/NiceAdmin/js/jquery.customSelect.min.js"></script>
    <script src="~/NiceAdmin/assets/chart-master/Chart.js"></script>

    <!--custome script for all page-->
    <script src="~/NiceAdmin/js/scripts.js"></script>
    <!-- custom script for this page-->
    <script src="~/NiceAdmin/js/sparkline-chart.js"></script>
    <script src="~/NiceAdmin/js/easy-pie-chart.js"></script>
    <script src="~/NiceAdmin/js/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="~/NiceAdmin/js/jquery-jvectormap-world-mill-en.js"></script>
    <script src="~/NiceAdmin/js/xcharts.min.js"></script>
    <script src="~/NiceAdmin/js/jquery.autosize.min.js"></script>
    <script src="~/NiceAdmin/js/jquery.placeholder.min.js"></script>
    <script src="~/NiceAdmin/js/gdp-data.js"></script>
    <script src="~/NiceAdmin/js/morris.min.js"></script>
    <script src="~/NiceAdmin/js/sparklines.js"></script>
    <script src="~/NiceAdmin/js/charts.js"></script>
    <script src="~/NiceAdmin/js/jquery.slimscroll.min.js"></script>
    <script src="~/Scripts/bootbox.min.js"></script>
    <script>
        //knob
        $(function () {
            $(".knob").knob({
                'draw': function () {
                    $(this.i).val(this.cv + '%')
                }
            })
        });

        //carousel
        $(document).ready(function () {
            $("#owl-slider").owlCarousel({
                navigation: true,
                slideSpeed: 300,
                paginationSpeed: 400,
                singleItem: true

            });
        });

        //custom select box

        $(function () {
            $('select.styled').customSelect();
        });

        /* ---------- Map ---------- */
        $(function () {
            $('#map').vectorMap({
                map: 'world_mill_en',
                series: {
                    regions: [{
                        values: gdpData,
                        scale: ['#000', '#000'],
                        normalizeFunction: 'polynomial'
                    }]
                },
                backgroundColor: '#eef3f7',
                onLabelShow: function (e, el, code) {
                    el.html(el.html() + ' (GDP - ' + gdpData[code] + ')');
                }
            });
        });
    </script>

</body>

</html>

E-Shop/E-Shop/Views/Shared/Layout.cshtml
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | E-Shopper</title>
    <link href="~/eshop/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/eshop/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/eshop/css/prettyPhoto.css" rel="stylesheet">
    <link href="~/eshop/css/price-range.css" rel="stylesheet">
    <link href="~/eshop/css/animate.css" rel="stylesheet">
    <link href="~/eshop/css/main.css" rel="stylesheet">
    <link href="~/eshop/css/responsive.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/eshop/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/eshop/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/eshop/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="~/eshop/images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>
    <header id="header">
        <!--header-->
        <div class="header_top">
            <!--header_top-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="contactinfo">
                            <ul class="nav nav-pills">
                                <li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
                                <li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="social-icons pull-right">
                            <ul class="nav navbar-nav">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header_top-->

        <div class="header-middle">
            <!--header-middle-->
            <div class="container">
                <div class="row">
                    <div class="col-md-4 clearfix">
                        <div class="logo pull-left">
                            <a href="/Home/Index"><img src="~/eshop/images/home/logo.png" alt="" /></a>
                        </div>

                    </div>
                    <div class="col-md-8 clearfix">
                        <div class="shop-menu clearfix pull-right">
                            <ul class="nav navbar-nav">

                                @if (User.Identity.IsAuthenticated)
                                {
                                    <li><a href="/User/Update"><i class="fa fa-user"></i> @Session["Ad"] @Session["Soyad"]</a></li>


                                    <li><a href="/Account/LogOut"><i class="fa fa-lock"></i> Çıkış Yap</a></li>
                                }

                                else
                                {
                                    <li><a href="/Account/Login"><i class="fa fa-lock"></i> Giriş Yap</a></li>
                                }

                                @if (User.IsInRole("Admin"))
                                {
                                    <li><a href="/Admin/Index"><i class="fa fa-lock"></i> Admin Paneli</a></li>
                                }



                                <li><a href="/Home/Index"> Anasayfa</a></li>

                                @if (User.Identity.IsAuthenticated)
                                {
                                    <li><a href="/Cart/Index"><img src="~/Content/Image/sepet.jpg" width="30" height="30" /><label style="color:red">@{Html.RenderAction("TotalCount", "Cart");}</label>Sepetim</a></li>
                                    <li><a href="/Sales/Index"><i class="fa fa-dollar"></i> Satışlarım</a></li>
                                }







                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header-middle-->


    </header><!--/header-->

    <div class="container">
        @RenderBody()
    </div>

    <footer id="footer">
        <!--Footer-->
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-sm-2">
                        <div class="companyinfo">
                            <h2><span>e</span>-shopper</h2>

                        </div>
                    </div>
                    <div class="col-sm-7">
                        <div class="col-sm-3">
                            <div class="video-gallery text-center">
                                <a href="#">
                                    <div class="iframe-img">
                                        <img src="~/eshop/images/home/iframe1.png" alt="" />
                                    </div>
                                    <div class="overlay-icon">
                                        <i class="fa fa-play-circle-o"></i>
                                    </div>
                                </a>
                                <p>Circle of Hands</p>
                                <h2>24 DEC 2014</h2>
                            </div>
                        </div>

                        <div class="col-sm-3">
                            <div class="video-gallery text-center">
                                <a href="#">
                                    <div class="iframe-img">
                                        <img src="~/eshop/images/home/iframe2.png" alt="" />
                                    </div>
                                    <div class="overlay-icon">
                                        <i class="fa fa-play-circle-o"></i>
                                    </div>
                                </a>
                                <p>Circle of Hands</p>
                                <h2>24 DEC 2014</h2>
                            </div>
                        </div>

                        <div class="col-sm-3">
                            <div class="video-gallery text-center">
                                <a href="#">
                                    <div class="iframe-img">
                                        <img src="~/eshop/images/home/iframe3.png" alt="" />
                                    </div>
                                    <div class="overlay-icon">
                                        <i class="fa fa-play-circle-o"></i>
                                    </div>
                                </a>
                                <p>Circle of Hands</p>
                                <h2>24 DEC 2014</h2>
                            </div>
                        </div>

                        <div class="col-sm-3">
                            <div class="video-gallery text-center">
                                <a href="#">
                                    <div class="iframe-img">
                                        <img src="~/eshop/images/home/iframe4.png" alt="" />
                                    </div>
                                    <div class="overlay-icon">
                                        <i class="fa fa-play-circle-o"></i>
                                    </div>
                                </a>
                                <p>Circle of Hands</p>
                                <h2>24 DEC 2014</h2>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>



        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <p class="pull-left">Copyright © 2022. Tüm Hakları Sakldır.</p>
                    <p class="pull-right">Designed by <span style="color:#f14a0b"></span></p>
                </div>
            </div>
        </div>

    </footer><!--/Footer-->
    <script src="~/eshop/js/jquery.js"></script>
    <script src="~/eshop/js/bootstrap.min.js"></script>
    <script src="~/eshop/js/jquery.scrollUp.min.js"></script>
    <script src="~/eshop/js/price-range.js"></script>
    <script src="~/eshop/js/jquery.prettyPhoto.js"></script>
    <script src="~/eshop/js/main.js"></script>
</body>
</html>