E-Shop/E-Shop/Controllers/SalesController.cs
using DataAccessLayer.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using EntityLayer.Entities;

namespace E_Shop.Controllers
{
    public class SalesController : Controller
    {
        // GET: Sales

        DataContext db = new DataContext();
        public ActionResult Index(int sayfa=1)
        {
            if (User.Identity.IsAuthenticated)
            {
                var kullaniciadi = User.Identity.Name;
                var kullanici = db.Users.FirstOrDefault(x => x.Email == kullaniciadi);
                var model = db.Sales.Where(x => x.UserId == kullanici.Id).ToList().ToPagedList(sayfa, 5);
                return View(model);
            }
            return HttpNotFound();
        }


        public ActionResult Buy(int id)
        {
            var model=db.Carts.FirstOrDefault(x => x.Id == id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Buy2(int id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var model = db.Carts.FirstOrDefault(x => x.Id == id);
                    var satis = new Sales
                    {
                        UserId = model.UserId,
                        ProductId = model.ProductId,
                        Quantity = model.Quantity,
                        Image = model.Image,
                        Price = model.Price,
                        Date = DateTime.Now,
                    };
                    db.Carts.Remove(model);
                    db.Sales.Add(satis);
                    db.SaveChanges();
                    ViewBag.islem = "Satın alma işlemi başarılı bir şekilde gerçekleşmiştir";
                }
            }
            catch (Exception)
            {

                ViewBag.islem = "Satın alma işlemi başarısız";
            }

            return View("islem");
        }

        public ActionResult BuyAll(decimal? Tutar)
        {
            if (User.Identity.IsAuthenticated)
            {
                var kullaniciadi = User.Identity.Name;
                var kullanici = db.Users.FirstOrDefault(x => x.Email == kullaniciadi);
                var model = db.Carts.Where(x => x.UserId == kullanici.Id).ToList();
                var kid = db.Carts.FirstOrDefault(x => x.UserId == kullanici.Id);
                if (model!=null)
                {
                    if (kid==null)
                    {
                        ViewBag.tutar = "Sepetinizde ürün bulunmamaktadır";
                    }
                    else if (kid!=null)
                    {
                        Tutar = db.Carts.Where(x => x.UserId == kid.UserId).Sum(x => x.Product.Price * x.Quantity);
                        ViewBag.Tutar = "Toplam Tutar=" + Tutar + "TL";
                    }

                    return View(model);
                }

                return View();
            }
            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult BuyAll2()
        {
            var username=User.Identity.Name;
            var kullanici=db.Users.FirstOrDefault(x=>x.Email==username);
            var model=db.Carts.Where(x=>x.UserId == kullanici.Id).ToList();
            int row = 0;

            foreach (var item in model)
            {
                var satis = new Sales
                {
                    UserId = model[row].UserId,
                    ProductId = model[row].ProductId,
                    Quantity = model[row].Quantity,
                    Price = model[row].Price,
                    Image = model[row].Image,
                    Date = DateTime.Now
                };

                db.Sales.Add(satis);
                db.SaveChanges();
                row++;
            }

            db.Carts.RemoveRange(model);
            db.SaveChanges();
            return RedirectToAction("Index", "Cart");
        }
    }
}

E-Shop/E-Shop/Views/Sales/Buy.cshtml
@model EntityLayer.Entities.Cart
@{
    ViewBag.Title = "Buy";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="modal-header">
    <h2>Satın Al</h2>
</div>

<div class="container">
    @using(Html.BeginForm("Buy2","Sales",FormMethod.Post))
            {
    <div class="modal-body">
        @Html.HiddenFor(x => x.Id)

        <div class="form-group">
            Kullanıcı Adı Soyadı: @Session["Ad"] @Session["Soyad"]
        </div>

        <div class="form-group">
            Ürün Bilgisi: @Html.DisplayFor(x => x.Product.Name, new { @class = "form-control" })
        </div>

        <div class="form-group">
            Adet: @Html.DisplayFor(x => x.Quantity, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <img src="~/Content/Image/@Model.Product.Image" width="80" height="80" />
        </div>

        <div class="form-group">
            Fiyat: @Html.DisplayFor(x => x.Price, new { @class = "form-control" })
        </div>
    </div>

    <div class="modal-footer" style="float:right">
        <button class="btn btn-success">Satın Al</button>
        <a href="/Cart/Index" class="btn btn-dark">İptal</a>
    </div>
            }
</div>

E-Shop/E-Shop/Views/Sales/BuyAll.cshtml
@model List<EntityLayer.Entities.Cart>
@{
    ViewBag.Title = "BuyAll";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="container">
    <div class="container">
        <h2>Merhaba @Session["Ad"] @Session["Soyad"] Satın Alma Sayfasına Hoşgeldiniz</h2>
    </div>


    <div class="container">
        @using (Html.BeginForm("BuyAll2", "Sales", FormMethod.Post))
        {
            foreach (var item in Model)
            {
                <div class="form-group">
                    <h5>ID: @Html.DisplayFor(x => item.Id)</h5>
                </div>

                <div class="form-group">
                    <h5>Ürün Ad: @Html.DisplayFor(x => item.Product.Name)</h5>
                </div>

                <div class="form-group">
                    <h5>Adet: @Html.DisplayFor(x => item.Quantity)</h5>
                </div>

                <div class="form-group">
                    <h5>Fiyat: @Html.DisplayFor(x => item.Price)</h5>
                </div>

                <div class="form-group">
                    <h5>Resim:<img src="~/Content/Image/@item.Product.Image" width="50" height="50" /></h5>
                </div>
            }

            <p style="color:red; text-align:center">@ViewBag.Tutar</p>
            <div class="container">
                <div class="form-group" style="float:left">
                    <button class="btn btn-success">Onay</button>
                </div>

                <div style="float:right">
                    <a href="/Cart/Index" class="btn btn-danger">İptal</a>
                </div>
            </div>
        }
    </div>
</div>

E-Shop/E-Shop/Views/Sales/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<EntityLayer.Entities.Sales>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Satış Listesi</h2>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Ürün Ad</th>
        <th>Adet</th>
        <th>Fiyat</th>
        <th>Resim</th>
        <th>Tarih</th>
    </tr>

    @foreach (var item in Model)
    {
        <tbody>
            <tr>
                <td>@item.Id</td>
                <td>@item.Product.Name</td>
                <td>@item.Quantity</td>
                <td>@item.Price</td>
                <td><img src="~/Content/Image/@item.Product.Image" width="90" height="90" /></td>
                <td>@Convert.ToDateTime(item.Date).ToString("dd/MM/yyyy")</td>
            </tr>
        </tbody>
    }
</table>
@Html.PagedListPager(Model, sayfa => Url.Action("Index", new { sayfa }), PagedListRenderOptions.Classic)

E-Shop/E-Shop/Views/Sales/islem.cshtml
@{
    ViewBag.Title = "islem";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>@ViewBag.islem</h2>