E-Shop/E-Shop/Controllers/CategoryController.cs
using BusinessLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_Shop.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        CategoryRepository categoryRepository = new CategoryRepository();
        public PartialViewResult CategoryList()
        {
            return PartialView(categoryRepository.List());
        }

        public ActionResult Details(int id)
        {
            var cat=categoryRepository.CategoryDetails(id);
            return View(cat);
        }
    }
}

E-Shop/E-Shop/Controllers/ProductController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Context;
using EntityLayer.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_Shop.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        ProductRepository productRepository = new ProductRepository();
        DataContext db = new DataContext();
        public PartialViewResult PopularProduct()
        {
            var product = productRepository.GetPopularProduct();
            ViewBag.popular = product;
            return PartialView();
        }

        public ActionResult ProductDetails(int id)
        {
            var details=productRepository.GetById(id);
            var yorum = db.Comments.Where(x => x.ProductId == id).ToList();
            ViewBag.yorum = yorum;
            return View(details);
        }

        [HttpPost]
        public ActionResult Comment(Comment data)
        {
            if (User.Identity.IsAuthenticated)
            {
                db.Comments.Add(data);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
    }
}

E-Shop/E-Shop/Views/Category/CategoryList.cshtml
@model List<EntityLayer.Entities.Category>

<div class="col-sm-3" style="margin-top:30px">
    <div class="left-sidebar">
        <div class="brands_products">
            <h2>KATEGORİLER</h2>
            <div class="brands-name">
                @foreach (var item in Model)
                {
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="/Category/Details/@item.Id"><span class="pull-right">(@item.Products.Count)</span>@item.Name</a></li>
                    </ul>
                }
            </div>
        </div>
    </div>
</div>

E-Shop/E-Shop/Views/Category/Details.cshtml
@model List<EntityLayer.Entities.Product>
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Layout.cshtml";
}


<section id="slider">
    <!--slider-->
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div id="slider-carousel" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
                        <li data-target="#slider-carousel" data-slide-to="1"></li>
                        <li data-target="#slider-carousel" data-slide-to="2"></li>
                    </ol>

                    <div class="carousel-inner">
                        <div class="item active">
                            <div class="col-sm-6">
                                <h1><span>E</span>-SHOPPER</h1>
                                <h2>Free E-Commerce Template</h2>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                                <button type="button" class="btn btn-default get">Get it now</button>
                            </div>
                            <div class="col-sm-6">
                                <img src="~/eshop/images/home/girl1.jpg" class="girl img-responsive" alt="" />
                                <img src="~/eshop/images/home/pricing.png" class="pricing" alt="" />
                            </div>
                        </div>
                        <div class="item">
                            <div class="col-sm-6">
                                <h1><span>E</span>-SHOPPER</h1>
                                <h2>100% Responsive Design</h2>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                                <button type="button" class="btn btn-default get">Get it now</button>
                            </div>
                            <div class="col-sm-6">
                                <img src="~/eshop/images/home/girl2.jpg" class="girl img-responsive" alt="" />
                                <img src="~/eshop/images/home/pricing.png" class="pricing" alt="" />
                            </div>
                        </div>

                        <div class="item">
                            <div class="col-sm-6">
                                <h1><span>E</span>-SHOPPER</h1>
                                <h2>Free Ecommerce Template</h2>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                                <button type="button" class="btn btn-default get">Get it now</button>
                            </div>
                            <div class="col-sm-6">
                                <img src="~/eshop/images/home/girl3.jpg" class="girl img-responsive" alt="" />
                                <img src="~/eshop/images/home/pricing.png" class="pricing" alt="" />
                            </div>
                        </div>

                    </div>

                    <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
                        <i class="fa fa-angle-left"></i>
                    </a>
                    <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
                        <i class="fa fa-angle-right"></i>
                    </a>
                </div>

            </div>
        </div>
    </div>
</section><!--/slider-->

<section>
    <div class="container">
        <div class="row">
            @Html.Action("CategoryList", "Category")

            <div class="col-sm-9 padding-right">
                <div class="features_items">
                    <!--features_items-->
                    <h2 class="title text-center">ÜRÜNLERİMİZ</h2>
                    @foreach (var item in Model)
                    {
                        <div class="col-sm-4">
                            <div class="product-image-wrapper">
                                <div class="single-products">
                                    <div class="productinfo text-center">

                                        <a href="/Product/Details/@item.Id"><img src="~/Content/Image/@item.Image" width="65" height="110" alt="" /></a>
                                        <h2>@item.Price</h2>
                                        <p>@item.Name</p>
                                        <a href="/Product/Details/@item.Id" class="btn btn-default add-to-cart">Ürün Detay</a>
                                    </div>

                                </div>

                            </div>
                        </div>
                    }

    



                </div><!--features_items-->
                @Html.Action("PopularProduct", "Product")

            </div>
        </div>
    </div>
</section>